### ISSUE TITLE
Advanced value sharing

### ISSUE THREAD

**Issue by Narzerus** [Narzerus/yakuza#1]
Sharing variables sometimes require special treatment (such as appending values to an array or doing mathematical operations to them)

The idea is to allow the developer to define custom sharing methods via the Yakuza api.

----

UPDATE:
On a second thought there should be Framework provided shares used as options:

```javascript
task.share('foo', {concat: true});
```

And if the user needs custom sharing behaviour not provided by the framework:

```javascript
Yakuza.task(..., ..., ...)
  .share(function (currentValue, newValue) {
    var current = currentValue || [];
    current.push(newValue);

    return current;
  });
```

**Comment by monitz87** [comment]
Good idea. Love how flexible the new framework is turning out to be.

**Comment by Narzerus** [comment]
This was implemented a couple fo weeks ago
