### ISSUE TITLE
node.js app file structure

### ISSUE THREAD

**Issue by ruicsh** [Narzerus/yakuza#56]
hey, do you have any suggestions on how to go about organising Yakuza on a nodejs application? I have  many different agents and would like to have each on its own file in a `agents` folder.

I would try a central file which includes all agents in a folder, just like Sequelize handles Models' definitions (http://sequelize.readthedocs.org/en/1.7.0/articles/express/#modelsindexjs), but it relies on an `Sequelize.import` method, that I think Yakuza lacks.

**Comment by RafaelVidaurre** [comment]
You can actually easily spread agents or tasks in different files. Yakuza is a singleton which saves every component of a scraper. Since node.js only loads a package **once** this works pretty well.

Example

``` javascript
// scraper.js
var Yakuza = require('yakuza');
Yakuza.scraper(...);
```

``` javascript
// agent1/agent.js
require('../scraper.js');
var Yakuza = require('yakuza');
Yakuza.agent(...);
```

``` javascript
// agent1/task1.js
require('agent1');
var Yakuza = require('yakuza');
Yakuza.task(...);
```

**Comment by ruicosta042** [comment]
yes thanks, it works like a charm, beautiful framework, great job

**Comment by RafaelVidaurre** [comment]
Glad I could help
